### ISSUE TITLE
Unable to build only safepdf

### ISSUE THREAD

**Issue by gruenich** [kmorel/UseLATEX#21]
This issue are actual two issues. I have a document with a psfig as input for LaTeX which should generate a PDF.

1. There is no `FORCE_SAFEPDF` or `FORCE_PS`. Is this a oversight or intentionally?
2.  `set(ENV{LATEX_DEFAULT_BUILD} safepdf)` is ignored, it builds all types like HTML which I don't want. And it fails with PDF, because pdfLaTeX does not understand ps stuff. I have to type `make safepdf` to only get the safepdf.

**Comment by kmorel** [comment]
1. This is intentional. The `FORCE_`* options are designed to remove targets that will not compile correctly (for example, because pdflatex does not understand ps stuff). If you want to support only compile paths that go through postscript, use the `FORCE_DVI` option. Both the ps and safepdf builds go through the dvi target. `FORCE_DVI` will disable the standard pdf target (that uses pdflatex).

2. I think you are using this feature wrong. The `LATEX_DEFAULT_BUILD` is not intended to force one particular build or another. It is simply suggesting which target to build for `all` (that is, what to build when you just type `make` without specifying a target). This is meant to reflect user preference for the default build. You might want to always build safepdf, but if you give your document to someone else, he or she might want to build dvi by default.

Your issue is probably that if the `LATEX_DEFAULT_BUILD` environment variable is not set (before cmake is called), then the default build will be `pdf` or `dvi` if `FORCE_DVI` is on. If you want to force the default build to be safepdf, you can add

    set(LATEX_DEFAULT_BUILD safepdf CACHE STRING "" FORCE)

To your `CMakeLists.txt`. You should put that line before your `latex_add_document` command.

**Comment by gruenich** [comment]
Thanks for clarifying and the updated FAQ.

Probably it is the best to change all LaTeX documents to work with pdfLaTeX anyway.
