### ISSUE TITLE
Invalid command on pdftops invocation

### ISSUE THREAD

**Issue by bergercookie** [kmorel/UseLATEX#23]
When turning the LATEX_DEFAULT_BUILD flag to html I get an error when executing the first pdftops commnad. I think the error is about the -r flag as this is not available in the pdftops manpage at all.
Here is the full error report: [pdftops_error.txt](https://github.com/kmorel/UseLATEX/files/598672/pdftops_error.txt)

I am running texlive2016 on OSX. pdftops is installed via homebrew - version 3.04

Thanks in advance,

**Comment by kmorel** [comment]
This was rather confusing. I have `pdftops` installed on my Mac with macports and my PC with MiKTeX, and the `-r` flag is supported in both.

After searching for answers for a while I got no clear answers, but I believe the issue is that there are two versions of `pdftops` floating around there. `pdftops` originally comes from a software package named Xpdf. The code was forked by a second project named poppler. It looks like both of my installations come from the poppler package. I suspect that the poppler project added the `-r` flag after it forked from Xpdf.

Nikos, I'd like you to verify two simple things for me. First, can you verify from your homebrew installation that your version of `pdftops` is coming from Xpdf or some variant that is not poppler? Second, can you try removing the `-r 600` flags from the `PDFTOPS_CONVERTER_FLAGS` CMake variable (using the CMake GUI or `ccmake`)? That would help verify that the resolution flag is indeed the problem.

**Comment by bergercookie** [comment]
>can you verify from your homebrew installation that your version of pdftops is coming from Xpdf
Comes from xpdf.
```
$ which pdftops
/usr/local/bin/pdftops
$ ll /usr/local/bin/pdftops
lrwxr-xr-x  1 nick  admin    33B Nov 17 17:04 /usr/local/bin/pdftops@ -> ../Cellar/xpdf/3.04_1/bin/pdftops
```

Indeed, the homebrew/x11/xpdf: stable 3.04 version is used, and this doesn't support the -r flag.

>can you try removing the -r 600 flags from the PDFTOPS_CONVERTER_FLAGS

Running directly the pdftops command (without the -r 600) without any error.
Also, as expected, using poppler instead of xpdf solves the problem as well.

So, if the "-r" options is not necessary for the html compilation, you might as well consider removing it just to support the xpdf version as well.

Thanks for the support Kenneth,

**Comment by kmorel** [comment]
I removed the `-r 600` from the default `PDFTOPS_CONVERTER_FLAGS`. The added benefit does not outweigh the issue of it breaking some of the builds.

**Comment by bergercookie** [comment]
👍
