### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by Alex-Vaduva** [kmorel/UseLATEX#33]
In version 1.7.3 the file UseLATEX.cmake has the following license:
# Under the terms of Contract DE-AC04-94AL85000, there is a non-exclusive
# license for use of this work by or on behalf of the
# U.S. Government. Redistribution and use in source and binary forms, with
# or without modification, are permitted provided that this Notice and any
# statement of authorship are reproduced on all copies.

Can I use this file in open source and commercial? Or only the U.S. Government has the right to use and redistribute?
 Thanks!

**Comment by kmorel** [comment]
You can use `UseLATEX.cmake` in a commercial application. This notice does not extend beyond that performed for the creation of this file, so it will not "infect" your commercial work. Since `UseLATEX.cmake` has already been openly distributed, this clause is already satisfied.

So, in short, yes you can use this file in either open source or commercial (or anything in between).

**Comment by Alex-Vaduva** [comment]
Thanks for the replay. But what if I want to distribute it to a Government (U.S. or another country? Can I distribute it? Or am I bound to the contract specified in the notice?

**Comment by kmorel** [comment]
The contract does not specify to whom you distribute the file to. You can distribute it to government entities (U.S. or foreign). The file is open and there are no export control issues.

The warning is not saying that only the U.S. Government gets to use the file. It is simply boilerplate that says because the U.S. Government funded the work, the U.S. Government gets to use the file. The point is moot, though, because everybody gets to use the file.

If you are still worried about the wording, you may consider using a newer version of `UseLATEX.cmake`. Starting with version 2.0 I formally went through the process to attach the BSD 3-Clause license. This notice is still there, but these files have the added license that better defines your rights to redistribute the file.
